config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :users do
      post :verify
    end
  end

  resource :phones do
    put :verify
  end
  resources :templates do
    get :add_more_sections, on: :collection
  end
  resources :profiles
  devise_for :users, :controllers => {:registrations => "registrations"}
  root "dashboard#index"

  resources :jobs do
    get 'openings', on: :collection
    get :change_status, on: :member
    resources :submissions do
      get :change_status, on: :member
      post :save_comment, on: :member
      get :add_attachments, on: :collection
      get :get_submission, on: :member
      resources :resumes
      resources :resume_sections
      resources :interviews
    end
  end
  
  get '/admin' => 'admin#index'

  get '/my_submissions' => 'submissions#my_submissions', as: 'my_submissions'

  get "/signup_success" => "home#signup_success"

end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :template
  has_many :submissions, dependent: :destroy
  has_many :interviews, dependent: :destroy
  has_many :job_skills
  has_many :skills, through: :job_skills
  belongs_to :user

  scope :active, -> {where(status: 'active')}
  scope :hold, -> {where(status: 'hold')}
  scope :closed, -> {where(status: 'closed')}


  validates :template_id, :title, :description, :location, :compensation, :hiring_user_id, :consultant_user_id, presence: true

  state_machine :status, :initial => :active do
    event :active do
      transition any => :active
    end

    event :hold do
      transition :active => :hold
    end

    event :close do
      transition :active => :closed, :hold => :closed
    end
  end

  searchable do
    text :title, :location
    string :skills, :multiple => true do
      skills.map(&:name)
    end
    text :skills do
      skills.map(&:name)
    end
  end

  def consultant
    User.find_by id: consultant_user_id
  end

  def hm
    User.find_by id: hiring_user_id
  end

  def active?
    status == "active"
  end

  def hold?
    status == "hold"
  end

  def closed?
    status == "closed"
  end

  def new_submissions
    @new_submissions ||= submissions.active
  end

  def processing_submissions
    @processing_submissions ||= submissions.process
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy, :change_status]
  layout "dashboard"

  def index
    @active_jobs = current_user.my_jobs.active
    @hold_jobs = current_user.my_jobs.hold
    @closed_jobs = current_user.my_jobs.closed
    authorize @active_jobs
    authorize @hold_jobs
    authorize @closed_jobs
  end

  def show
    @submission_record = @job.submissions.find_by_user_id current_user.id
  end

  def new
    @job = Job.new
    @job_skills = ''
    authorize @job
  end

  def edit
    @job_skills = @job.job_skills.any? ? @job.skills.collect(&:name).join(',') : ''
    authorize @job
  end

  def create
    # raise params.inspect
    @job = current_user.consultant_jobs.new(job_params)
    authorize @job
    respond_to do |format|
      if @job.save
        skills = params[:job][:job_skills][:name]
        skills = skills.present? ? skills.split(',') : []
        if skills.any?
          skills.each do|s|
            skill = Skill.find_or_create_by name: s.downcase
            JobSkill.where(job_id: @job.id, skill_id: skill.id).first_or_create
          end
        end
        format.html { redirect_to @job, notice: 'Job was successfully posted.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def openings
    @search = Job.search do
      fulltext (params['what'].present? ? params['what'] : "") + ' ' + (params['where'].present? ? params['where'] : "")
      paginate :page => params[:page], :per_page => 10
    end
    @jobs = @search.results
  end

  def update
    respond_to do |format|
      authorize @job
      if @job.update(job_params)
        @job.job_skills.destroy_all
        skills = params[:job][:job_skills][:name]
        skills = skills.present? ? skills.split(',') : []
        if skills.any?
          skills.each do|s|
            skill = Skill.find_or_create_by name: s.downcase
            JobSkill.find_or_create_by job_id: @job.id, skill_id: skill.id
          end
        end
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @job
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def change_status
    if params[:status] == 'active'
      @job.active
    elsif params[:status] == 'hold'
      @job.hold
    elsif params[:status] == 'close'
      @job.close
    end
    redirect_to :back
  end

  private
    def set_job
      @job = Job.find(params[:id])
    end

    def job_params
      params.require(:job).permit(:title, :description, :location, :template_id, :consultant_user_id, :hiring_user_id, :job_type, :start_date, :duration, :compensation,:experience)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<div class="row">
  <div class="col-md-11">
    <%= simple_form_for(@job, html: {class: 'form-horizontal', autocomplete: 'off',onkeypress: "return event.keyCode != 13;"}, wrapper: :horizontal_form) do |f| %>
    <%= f.error_notification %>

    <% if f.object.new_record? %>

      <div class="form-group">
        <div class="col-md-offset-3 col-md-9">
          <strong>
            Pick Template from the following or <%= link_to 'Create Template', new_template_path %>
          </strong>
        </div>
        <div class="col-md-offset-3">
        </div>
      </div>

      <div class="form-group">
        <div class="col-md-offset-3 col-md-9">
          <%= f.input :template_id,
                      :collection => current_user.templates.map { |t| [t.id, t.name] },
                      :label_method => :last,
                      :value_method => :first,
                      :label => false,
                      :item_label_class => 'radio-inline',
                      :item_wrapper_tag => false,
                      :as => :radio_buttons, readonly: true %>
        </div>
      </div>
    <% else %>
      <div class="form-group">
        <label class="col-sm-3 control-label">Template</label>

        <div class="col-sm-9">
          <!--<input class="string optional form-control" type="text" value="Hyderabad India" name="job[location]" id="job_location">-->
          <label class="form-control" style="background: transparent;border:none;box-shadow:inherit;">
            <%= f.object.template.name %>
          </label>
        </div>
      </div>
    <% end %>

    <div class="form-group">
      <label class="col-sm-3 control-label">Hiring Manager</label>

      <div class="col-md-9">
        <%= f.select :hiring_user_id, Role.where(name: "hm").first.users.map { |l| [l.email, l.id] }, {}, class: 'form-control' %>
      </div>
    </div>
      <%= f.input :title %>
      <%= f.input :location, input_html: {class: 'us_loc_auto_comp'} %>
      <div class="form-group">
        <%= f.label :job_type, class: "col-sm-3 control-label" do %>
          Position Type
        <% end %>
        <div class="col-sm-9">
          <%= label_tag :inline_radio_2, class: "radio-inline" do %>
            <%= f.radio_button :job_type, 'permanent', checked: ((f.object.job_type == 'permanent' || f.object.new_record?) ? true : false), class: 'job_type', style: 'margin-top: 4px' %>
            Permanent
          <% end %>
          <%= label_tag :inline_radio_1, class: "radio-inline" do %>
            <%= f.radio_button :job_type, 'contract', checked: (f.object.job_type == 'contract' ? true : false), class: 'job_type', style: 'margin-top: 4px' %>
            Contract
          <% end %>
        </div>
      </div>

      <%= content_tag :div, class: 'contract_fields ' + (f.object.job_type == 'contract' ? '' : 'hide') do%>
        <%= f.input :duration, as: :float, hint: "Duration in months" %>
      <% end %>
      <%= f.input :start_date,as: :string, input_html: {class: 'has_datepicker form-control'} %>

      <%= f.input :description, input_html: {:class => 'ckeditor'} %>
      <%= f.simple_fields_for :job_skills do|s|%>
      <%= s.input :name,label: "Skills", input_html: {value: @job_skills,placeholder: 'Enter comma separate ',data: {role: "tagsinput"}} %>
      <% end %>

      <%= f.input :compensation, placeholder: "Eg: 500000" ,hint: "Salary per annum. Eg: 500000 " %>
      <%= f.input :experience, as: :float, hint: "Experience in Years.", placeholder: 'Eg: 2.6' %>
    <div class="form-group">
      <div class="col-md-offset-3 col-md-9">
        <%= f.button :submit, class: 'btn-primary' %>
      </div>
    </div>
  <% end %>
  </div>
</div>

<style>
  .bootstrap-tagsinput{
    width: 100%;
  }
</style>

<script>
  $(".job_template_id").removeClass("form-group");
  // location auto completer
  $('.us_loc_auto_comp').on('click',function (e) {
    var id = $(this).attr('id');
    var inputxx = document.getElementById(id);
    var countryRestrict = {'country': 'us'};
    var optionsxx = {
      types: ['geocode'],
      componentRestrictions: countryRestrict
    };

    var autocomplete = new google.maps.places.Autocomplete(inputxx, optionsxx);
    google.maps.event.addListener(autocomplete, 'place_changed', function () {
      var place = autocomplete.getPlace();
    });
  });

  $('.job_type').on('change', function(e){
    var checked = $('.job_type:checked').val();
    if(checked=='contract'){
      $('.contract_fields').removeClass('hide');
    }else{
      $('.contract_fields').addClass('hide');
    }
  });

  $(".has_datepicker").datetimepicker({
    timepicker: false,
    format: 'Y/m/d',
    minDate:'+1970/01/02'
  });

</script>

app/views/jobs/_jobs.html.erb
<table class="table table-bordered table-responsive">
  <thead>
  <tr>
    <th class="col-md-3">TITLE</th>
    <th class="col-md-3">POSTED</th>
    <th class="col-md-3">LOCATION</th>
    <th class="col-md-3">ACTIONS</th>
  </tr>
  </thead>

  <tbody>
  <% if jobs.any? %>
    <% jobs.each do |job| %>
    <tr>
      <td class="col-md-3">
        <%= link_to job.title, job_path(job) %>
        <% if job.new_submission_display? %>
          <label class="label-danger label">New(<%= job.new_submission_size %>)</label>
        <% end %>
      </td>
      <td class="col-md-3"><%= job.created_at.strftime("%b %d, %Y %H %p") %></td>
      <td class="col-md-3"><%= job.location %></td>
      <td class="col-md-3">
        <% if policy(job).edit? %>
          <%= link_to 'Edit', edit_job_path(job) %>&nbsp;&nbsp;
          <% if job.active? %>
            <%= link_to 'Hold', change_status_job_path(job, status: 'hold') %>&nbsp;&nbsp;
            <%= link_to 'Close', change_status_job_path(job, status: 'close') %>&nbsp;&nbsp;
          <% elsif job.hold? %>
            <%= link_to 'Active', change_status_job_path(job, status: 'active') %> &nbsp;&nbsp;
            <%= link_to 'Close', change_status_job_path(job, status: 'close') %> &nbsp;&nbsp;
          <% elsif job.closed? %>
            <%= link_to 'Active', change_status_job_path(job, status: 'active') %> &nbsp;&nbsp;
          <% end %>
        <% else %>
          <% if job.user_submitted? %>
            <a href="#" class="btn btn-default btn-sm disabled" role="button">Submitted</a>
          <% elsif current_user.candidate? %>
            <%= link_to "Apply", new_job_submission_path(job), class: 'btn btn-sm btn-info' %>
          <% end %>
        <% end %>

        <% if policy(job).update? %>
          <%= link_to "View Submissions(#{job.submissions_count})", job_submissions_path(job) %>
        <% end %>
        </tr>
  <% end %>
  <% else %>
    <tr>
      <td colspan="4">No Jobs found.</td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/jobs/edit.html.erb
<h1 style="text-align: center; margin-bottom: 5%;", class="text-primary">Editing Job</h1>

<%= render 'form' %>

app/views/jobs/index.html.erb
<h1 class="text-primary">Listing Jobs</h1>

<div class="pull-right">
  <% if policy(@active_jobs).create? %>
    <%= link_to 'Post Job', new_job_path %>
  <% end %>
</div>

<ul id="myTabs" class="nav nav-tabs" role="tablist">
  <li role="presentation" class="active">
    <a href="#active" id="active-tab" role="tab" data-toggle="tab" aria-controls="active" aria-expanded="true">Active</a></li>
  <li role="presentation" class="">
    <a href="#hold" role="tab" id="hold-tab" data-toggle="tab" aria-controls="hold" aria-expanded="false">Hold</a>
  </li>
  <li role="presentation" class="">
    <a href="#close" role="tab" id="close-tab" data-toggle="tab" aria-controls="close" aria-expanded="false">Close</a>
  </li>
</ul>
<div id="myTabContent" class="tab-content">
  <div role="tabpanel" class="tab-pane fade active in" id="active" aria-labelledby="active-tab">
    <%= render partial: 'jobs', locals: {jobs: @active_jobs} %>
  </div>
  <div role="tabpanel" class="tab-pane fade" id="hold" aria-labelledby="hold-tab">
    <%= render partial: 'jobs', locals: {jobs: @hold_jobs} %>
  </div>
  <div role="tabpanel" class="tab-pane fade" id="close" aria-labelledby="close-tab">
    <%= render partial: 'jobs', locals: {jobs: @closed_jobs} %>
  </div>
</div>

app/views/jobs/new.html.erb
<h1 style="text-align: center; margin-bottom: 5%", class="text-primary">Post Job</h1>
<div class="container-fluid">
  <% if current_user.templates.count == 0 %>
    <div class="alert alert-danger" role="alert">
      Need template before posting job. Click here to <%= link_to 'Create Template.', new_template_path %>
    </div>
  <% end %>

  <%= render 'form' %>

</div>

app/views/jobs/openings.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="well">
      <%= form_tag openings_jobs_path, method: :get, class: 'form-inline' do %>
        <div class="form-group">
          <%= text_field_tag :what, params[:what], class: 'form-control input-lg', placeholder: 'Skill', autocomplete: :off %>
        </div>
        <div class="form-group">
          <%= text_field_tag :where, params[:where], class: 'form-control input-lg loc_auto_comp', placeholder: 'Location' %>
        </div>
        <%= submit_tag :search, class: 'btn btn-success btn-lg' %>
      <% end %>
      <small class="text-muted">Example: UI Developer, "Web Developer"</small>
    </div>
  </div>
</div>
<% @jobs.each do |job| %>
  <div class="row">
    <div class="col-md-10">
      <h4><%= link_to job.title, job_path(job) %></h4>

      <p>
        <% if job.job_type.present? %>
          <span class="label label-primary"><%= job.job_type %></span>&nbsp;|&nbsp;
        <% end %>
        <% if job.job_type == 'permanent' %>
          <span><%= number_to_currency(job.compensation, unit: "$ ") %>.</span>&nbsp;|&nbsp;
        <% elsif job.job_type == 'contract' %>
          <span>Duration <%= job.duration %> months.</span>&nbsp;|&nbsp;
        <% end %>
        <% if job.experience.present? %>
          <span>Exp: <%= job.experience %> Years</span>&nbsp;|&nbsp;
        <% end %>
        <span><i class="glyphicon glyphicon-map-marker"></i>&nbsp;<%= job.location %></span>&nbsp;|&nbsp;
      <span>
        <i class="glyphicon glyphicon-calendar"></i>&nbsp;<i>posted <%= time_ago_in_words job.created_at %> ago</i>
      </span>
      </p>
    </div>
    <div class="col-md-2">
      <% if job.submissions.find_by_user_id current_user.id %>
        <%= link_to "Submitted", '#', class: 'btn btn-success btn-sm disabled' %>
      <% elsif current_user.candidate? %>
        <%= link_to "Apply", new_job_submission_path(job), class: 'btn btn-sm btn-info' %>
      <% end %>
    </div>
  </div>
  <% if job.skills.any? %>
    <div class="row">
      <div class="col-md-12">
        <% job.skills.each do |skill| %>
          <span class="label label-default"><%= skill.name %></span>
        <% end %>
      </div>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-12">
      <p>
        <%= raw HTML_Truncator.truncate(job.description, 50) %>
      </p>
    </div>
  </div>
  <hr style="margin: 5px">
<% end %>
<div class="row text-center">
  <%= will_paginate @jobs, renderer: BootstrapPagination::Rails %>
</div>

<style>
  .form-inline .form-group input {
    width:350px;
  }
</style>

app/views/jobs/show.html.erb
<div class="row">
  <div class="col-md-10">
    <h2 class="text-primary">
      <%= @job.title %>
    </h2>

    <p>
      <% if @job.job_type.present? %>
        <span class="label label-primary"><%= @job.job_type %></span>&nbsp;|&nbsp;
      <% end %>
      <% if @job.job_type == 'permanent' %>
        <span><%= number_to_currency(@job.compensation, unit: "$ ") %>.</span>&nbsp;|&nbsp;
      <% elsif @job.job_type == 'contract' %>
        <span>Duration <%= @job.duration %> months.</span>&nbsp;|&nbsp;
      <% end %>
      <% if @job.experience.present? %>
        <span>Exp: <%= @job.experience %> Years</span>&nbsp;|&nbsp;
      <% end %>
      <span><i class="glyphicon glyphicon-map-marker"></i>&nbsp;<%= @job.location %></span>&nbsp;|&nbsp;
      <span>
        <i class="glyphicon glyphicon-calendar"></i>&nbsp;<i>posted <%= time_ago_in_words @job.created_at %> ago</i>
      </span>
    </p>
  </div>
  <div class="col-md-2">
    <% if policy(@job).edit? %>
      <%= link_to 'Edit', edit_job_path(@job), class: 'btn btn-primary btn-sm' %>
      <%= link_to 'Delete', @job, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger btn-sm' %>
    <% end %>
    <% unless policy(@job).update? || policy(@job).destroy? %>
      <% if @submission_record %>
        <a href="#" class="btn btn-success btn-sm disabled btn-block" role="button">Submitted</a>
      <% else %>
        <%= link_to "Apply", new_job_submission_path(@job), class: 'btn btn-info btn-sm btn-block' %>
      <% end %>
    <% end %>
  </div>
</div>
<% if @job.skills.any? %>
  <div class="row">
    <div class="col-md-12">
      <% @job.skills.each do |skill| %>
        <span class="label label-default"><%= skill.name %></span>
      <% end %>
    </div>
  </div>
<% end %>

<hr style="margin: 5px">
<div class="row">
  <div class="col-md-10">
    <h2 class="text-primary">Description:</h2>
    <p><%= raw @job.description %></p>
    </P>
  </div>
</div>