config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :users do
      post :verify
    end
  end

  resource :phones do
    put :verify
  end
  resources :templates do
    get :add_more_sections, on: :collection
  end
  resources :profiles
  devise_for :users, :controllers => {:registrations => "registrations"}
  root "dashboard#index"

  resources :jobs do
    get 'openings', on: :collection
    get :change_status, on: :member
    resources :submissions do
      get :change_status, on: :member
      post :save_comment, on: :member
      get :add_attachments, on: :collection
      get :get_submission, on: :member
      resources :resumes
      resources :resume_sections
      resources :interviews
    end
  end
  
  get '/admin' => 'admin#index'

  get '/my_submissions' => 'submissions#my_submissions', as: 'my_submissions'

  get "/signup_success" => "home#signup_success"

end

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <% alert_class = case key
                     when "notice" then "success"
                     when "alert" then "danger"
                     else key
                   end %>
  <%= content_tag :div, class: "alert alert-#{alert_class}" do %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= value %>
  <% end %>
<% end %>

app/views/shared/_left_navigation.slim
div class="panel panel-info"
  div class="panel-heading"
    h5
      = current_user.user_role_name
  div class="panel-body"
    ul.nav.nav-stacked
      -if current_user.consultant?
        li
          = link_to 'Templates', templates_path, class: "#{params[:controller] == 'templates' ? 'active' : ''} "
      - if current_user.consultant? || current_user.hm?
        li
          = link_to "My Jobs", jobs_path, class: "#{params[:controller] == 'jobs' && params[:action] == 'index' ? 'active' : ''} "
      -if current_user.candidate?
        li
          = link_to "Openings", openings_jobs_path, class: "#{params[:controller] == 'jobs' && params[:action] == 'openings' ? 'active' : ''} "
        li
          = link_to "Submissions",my_submissions_path, class: "#{params[:controller] == 'submissions' && params[:action] == 'my_submissions' ? 'active' : ''} "
-if current_user.admin? 
  div class="panel panel-info"
    div class="panel-heading"
      h5
        = current_user.role.label
    div class="panel-body"
      ul.nav.nav-stacked    
          li
            = link_to "All Users", admin_users_path, class: "#{params[:controller] == 'admin' ? 'active' : ''} " 
css:
  .active{
    text-decoration: none;
    background-color: #DCDCDC;
  }