config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :users do
      post :verify
    end
  end

  resource :phones do
    put :verify
  end
  resources :templates do
    get :add_more_sections, on: :collection
  end
  resources :profiles
  devise_for :users, :controllers => {:registrations => "registrations"}
  root "dashboard#index"

  resources :jobs do
    get 'openings', on: :collection
    get :change_status, on: :member
    resources :submissions do
      get :change_status, on: :member
      post :save_comment, on: :member
      get :add_attachments, on: :collection
      get :get_submission, on: :member
      resources :resumes
      resources :resume_sections
      resources :interviews
    end
  end
  
  get '/admin' => 'admin#index'

  get '/my_submissions' => 'submissions#my_submissions', as: 'my_submissions'

  get "/signup_success" => "home#signup_success"

end

app/models/user.rb
class User < ActiveRecord::Base
  rolify

  attr_accessor :role_id
  has_many :templates, dependent: :destroy
  has_many :submissions, dependent: :destroy
  has_many :consultant_jobs, class_name: 'Job', foreign_key: 'consultant_user_id'
  has_many :hm_jobs, class_name: 'Job', foreign_key: 'hiring_user_id'
  has_many :interviews, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :async,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  after_create :build_profile
  # after_initialize :check_role, if: Proc.new {|u| u.role.nil?}
  has_one :profile, :dependent => :destroy

  def to_s
    "#{profile.first_name} #{profile.last_name}"
  end

  def my_jobs
    if hm?
      hm_jobs
    elsif consultant?
      consultant_jobs
    end
  end

  # Override devise confirm! message
  def confirm!
    welcome_email
    super
  end

  def full_name
    (profile.first_name.to_s + " " + profile.last_name.to_s) rescue ''
  end

  def display_picture
    profile.picture.present? ? profile.picture : 'profile.png'
  end

  def display_thumb_picture
    (profile.picture.present? and profile.picture.thumb.present?) ? profile.picture.thumb : 'profile.png'
  end

  def role
    @role ||= roles.first
  end

  def role_name
    @role_name ||= role ? role.name : nil
  end

  def user_role_name
    if consultant?
      @name ||= Role.where(name: "consultant").first.label
    elsif hm?
      @name ||= Role.where(name: "hm").first.label
    elsif candidate?
      @name ||= Role.where(name: "candidate").first.label
    end
  end

  def candidate?
    @candidate ||= roles.pluck(:name).include?("candidate")
  end

  def hm?
    @hm ||= roles.pluck(:name).include?("hm")
  end

  def consultant?
    @consultant ||= roles.pluck(:name).include?("consultant")
  end

  def admin?
    @admin ||= roles.pluck(:name).include?("admin")
  end

  def new_token!
    SecureRandom.hex(16).tap do |random_token|
      update_attributes token: random_token
      Rails.logger.info("Set new token for user #{ id }")
    end
  end

  def remove_token!
    update_attributes token: nil
    Rails.logger.info("Remove token for user #{ id }")
  end

  private

  def check_role
    self.add_role :candidate
  end

  def welcome_email
    UserMailer.welcome_email(self).deliver_now
  end

  def build_profile
    p = Profile.new
    p.user = User.last
    p.first_name = User.last.email.split('@').first
    p.save(validate: false)
  end
end

app/controllers/admin/users_controller.rb
module Admin

  class UsersController < AdminController
    before_action :find_user, only: [:edit, :update, :destroy]
    
    layout 'dashboard'

    def index
      @users = User.joins(:roles).where("roles.name = ? OR roles.name = ? OR roles.name = ?", 'candidate', 'hm', 'consultant')
      authorize :"admin/user"
    end

    def verify
      @user = User.find(params[:user_id])
      if @user.update(verification: params[:verification])
        flash[:success] = "User successfully verified!!"
      else
        flash[:error] = "Error verifying User."
      end
      redirect_to admin_users_path
    end

    def new
      @user = User.new
    end

    def destroy
    end

    def edit
    end

    def create
      ActiveRecord::Base.transaction do
        @user = User.new(user_params)
        @user.password = user_params[:password]
        @user.password_confirmation = user_params[:password]
        # @user.skip_confirmation!
        @user.add_role params[:role].to_sym
        if @user.save(validate: false)
          profile = @user.profile
          profile.first_name = user_params[:first_name]
          profile.last_name = user_params[:last_name]
          profile.save(validate: false)
          flash[:notice] = "User created."
          redirect_to admin_users_path
        else
          render 'new'
        end
      end
    end

    def update
      if @user.update(user_params)
        flash[:notice] = 'User updated'
        redirect_to admin_users_path
      else
        render 'edit'
      end
    end

    private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password)
    end

    def find_user
      @user = User.where(params[:id]).first
    end
  end
end

app/views/admin/users/_form.html.erb
<div class="row">
  <div class="col-sm-7 col-sm-offset-1" style="margin-top: 3%">
    <div class="panel panel-info">
      <div class="panel-heading">
        <h3 class="panel-title">
          <span class="glyphicon glyphicon-user"></span>
            Creating New User
        </h3>
       </div>
      <div class="panel-body">
        <%= form_for([:admin, @user]) do |f| %>
          <div class="form-group">
            <%= f.label :email, class: "col-sm-4 control-label" %>
            <div class="col-sm-7">
              <div class="input-group">
                <span class="input-group-addon">
                  <i class="glyphicon glyphicon-envelope"></i>
                </span>
                <%= f.text_field :email, class: 'form-control' %>
              </div>
            </div>
          </div>
         
          <div class="form-group">
            <%= f.label :password, class: 'col-sm-4 control-label required' %>
            <div class="col-sm-7">
              <%= f.text_field :password, class: 'form-control', required: true %>
            </div>
          </div>

          <div class="form-group">
            <label class="col-sm-3 control-label">
              Role:
            </label>

            <div class="col-sm-12">
              <% Role.where("name = ? OR name = ? OR name = ?", 'hm', 'consultant', 'candidate').each do |role| %>
                <label class="radio-inline">
                  <input type="radio" name="role" value="<%= role.name %>" required><%= role.label %>
                </label>
              <% end %>
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-offset-4 col-sm-4"><br/>
              <%= f.submit class: 'btn btn-primary' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<h1 class="text-primary"> All Users </h1>
<a class="pull-right" href="/admin/users/new"> New User </a>
<table class="table table-bordered table-responsive">
  <thead>
    <tr>
      <th width="10">ID</th>
      <th width="20">Name</th>
      <th width="20">Email</th>
      <th width="10">Role</th>
      <th width="20">Verification</th>
      <th width="20">Action</th>
    </tr>
  </thead>
  <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td><%= user.full_name %></td>
          <td><%= user.email %></td>
          <td><%= user.role.label %></td>
          <td>
            <% if user.verification %>
             <span class="label label-success">Verified</span>
             <% else %>
              Unverified
            <% end %>
          </td>
          <td class="actions">
            <% unless user.verification %>
              <%= link_to 'Verify', admin_user_verify_path(user, verification: 1), method: :post, class: 'btn btn-primary' %>
            <% end %>
              <%#= link_to 'Edit', edit_admin_user_path(user), class: 'btn btn-default' %>
              <%#= link_to 'Delete' , admin_path(user), class: 'btn btn-default', method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
  </tbody>
</table>

app/views/admin/users/new.html.erb
<h1 class="text-primary"> New User </h1>
<%= link_to 'Back', admin_users_path, class: 'pull-right' %>
<%= render 'form' %>