config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :users do
      post :verify
    end
  end

  resource :phones do
    put :verify
  end
  resources :templates do
    get :add_more_sections, on: :collection
  end
  resources :profiles
  devise_for :users, :controllers => {:registrations => "registrations"}
  root "dashboard#index"

  resources :jobs do
    get 'openings', on: :collection
    get :change_status, on: :member
    resources :submissions do
      get :change_status, on: :member
      post :save_comment, on: :member
      get :add_attachments, on: :collection
      get :get_submission, on: :member
      resources :resumes
      resources :resume_sections
      resources :interviews
    end
  end
  
  get '/admin' => 'admin#index'

  get '/my_submissions' => 'submissions#my_submissions', as: 'my_submissions'

  get "/signup_success" => "home#signup_success"

end

app/models/resume.rb
class Resume < ActiveRecord::Base
  belongs_to :submission
  has_many :resume_sections, dependent: :destroy
  belongs_to :template

  accepts_nested_attributes_for :resume_sections, :reject_if => lambda { |a| a[:video].blank? }, :allow_destroy => true
  validates_presence_of :submission_id, :template_id
end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :set_resume, :find_job, :find_submission
  layout 'dashboard'

  def show
    @resume_sections ||= @resume.resume_sections.order('id asc')
    @comments = @submission.comments.where(user_id: current_user.id, label: @submission.status)
  end

  def update
    # @resume.update_attributes!(resume_params)
    resume_params[:resume_sections_attributes].each do |k, v|
      resume_section = ResumeSection.find v["id"]
      resume_section.update_attributes(v)
    end
    case params[:next_action]
      when "hire"
        @submission.hire
      when "interview"
        redirect_to new_job_submission_interview_path(@job, @submission)
        return
      when 'process'
        @submission.process
      when "park"
        @submission.park
        @submission.update_attribute(:activity_user_id, current_user.id)
        Notifier.parked_email_to_consultant(@submission).deliver_now if current_user.hm?
        comment = @submission.comments.create({
                                                description: params[:comment],
                                                user_id: current_user.id,
                                                label: params[:next_action]
                                              })
      when "discard"
        @submission.discard
        @submission.update_attribute(:activity_user_id, current_user.id)
        Notifier.discard_email_to_consultant(@submission).deliver_now if current_user.hm?
        comment = @submission.comments.create({
                                                description: params[:comment],
                                                user_id: current_user.id,
                                                label: params[:next_action]
                                              })
      when "undecided"
        @submission.un_decide
      else
    end
    redirect_to job_submissions_path(@job)
  end

  private

  def resume_params
    params.require(:resume).permit({:resume_sections_attributes => [:id, :consultant_rating, :hiring_manager_rating]})
  end

  def set_resume
    @resume = Resume.find(params[:id])
  end

  def find_job
    @job = Job.find(params[:job_id])
  end

  def find_submission
    @submission = Submission.find(params[:submission_id])
  end
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/resumes/_decisions.html.erb
<div class="row">
  <% if current_user.hm? %>
    <% if @submission.processing? %>
      <%= link_to 'Hire', change_status_job_submission_path(@job, @submission, status: 'hire'), class: 'btn btn-default', style: "margin: 1% 0;", data: {status: 'hire'}, confirm: "Are you sure you want to hire the candidate?" %>
      <%= link_to 'Interview', new_job_submission_interview_path(@job, @submission), class: 'btn btn-default', style: "margin: 1% 0;" %>
      <%#= link_to 'Park', '#', class: 'btn btn-default comment-btn', style: "margin: 1% 0;", data: {status: 'park'} %>
      <%= link_to 'Undecided', change_status_job_submission_path(@job, @submission, status: 'un_decided'), class: 'btn btn-default', style: "margin: 1% 0;" %>
      <%= link_to 'Reject', '#', class: 'btn btn-default comment-btn', style: "margin: 1% 0;", data: {status: 'discard'} %>
    <% elsif @submission.un_decided? %>
      <%= link_to 'Hire', change_status_job_submission_path(@job, @submission, status: 'hire'), class: 'btn btn-default', style: "margin: 1% 0;", data: {status: 'hire'}, confirm: "Are you sure you want to hire the candidate?" %>
      <%= link_to 'Interview', new_job_submission_interview_path(@job, @submission), class: 'btn btn-default', style: "margin: 1% 0;" %>
      <%#= link_to 'Park', '#', class: 'btn btn-default comment-btn', style: "margin: 1% 0;", data: {status: 'park'} %>
      <%= link_to 'Reject', '#', class: 'btn btn-default comment-btn', style: "margin: 1% 0;", data: {status: 'discard'} %>
    <% elsif @submission.parked? %>
      <%= link_to 'Hire', change_status_job_submission_path(@job, @submission, status: 'hire'), class: 'btn btn-default', style: "margin: 1% 0;", data: {status: 'hire'}, confirm: "Are you sure you want to hire the candidate?"%>
      <%= link_to 'Interview', new_job_submission_interview_path(@job, @submission), class: 'btn btn-default', style: "margin: 1% 0;" %>
      <%= link_to 'Undecided', change_status_job_submission_path(@job, @submission, status: 'un_decided'), class: 'btn btn-default', style: "margin: 1% 0;" %>
    <% elsif @submission.interview_scheduled? %>
      <%= link_to 'Hire', change_status_job_submission_path(@job, @submission, status: 'hire'), class: 'btn btn-default', style: "margin: 1% 0;", data: {status: 'hire'}, confirm: "Are you sure you want to hire the candidate?"%>
      <%= link_to 'Edit Interview', edit_job_submission_interview_path(@job, @submission, @submission.interview), class: 'btn btn-default', style: "margin: 1% 0;" %>
      <%#= link_to 'Park', '#', class: 'btn btn-default comment-btn', style: "margin: 1% 0;", data: {status: 'park'} %>
      <%= link_to 'Undecided', change_status_job_submission_path(@job, @submission, status: 'un_decided'), class: 'btn btn-default', style: "margin: 1% 0;" %>
    <% end %>
  <% elsif current_user.consultant? %>
    <% if @submission.submitted? %>
      <%= link_to 'Submit to HM', change_status_job_submission_path(@job, @submission, status: 'process'), class: 'btn btn-default', style: "margin: 1% 0;" %>
      <%#= link_to 'Park', '#', class: 'btn btn-default comment-btn', style: "margin: 1% 0;", data: {status: 'park'} %>
      <%= link_to 'Undecided', change_status_job_submission_path(@job, @submission, status: 'un_decided'), class: 'btn btn-default', style: "margin: 1% 0;" %>
      <%= link_to 'Reject', '#', class: 'btn btn-default comment-btn', style: "margin: 1% 0;", data: {status: 'discard'}  %>
    <% elsif @submission.un_decided? %>
      <%= link_to 'Submit to HM', change_status_job_submission_path(@job, @submission, status: 'process'), class: 'btn btn-default', style: "margin: 1% 0;" %>
      <%#= link_to 'Park', '#', class: 'btn btn-default comment-btn', style: "margin: 1% 0;", data: {status: 'park'} %>
      <%= link_to 'Reject', '#', class: 'btn btn-default comment-btn', style: "margin: 1% 0;", data: {status: 'discard'} %>
    <% elsif @submission.parked? %>
      <%= link_to 'Submit to HM', change_status_job_submission_path(@job, @submission, status: 'process'), class: 'btn btn-default', style: "margin: 1% 0;"  %>
      <%= link_to 'Undecided', change_status_job_submission_path(@job, @submission, status: 'un_decided'), class: 'btn btn-default', style: "margin: 1% 0;" %>
      <%= link_to 'Reject', '#', class: 'btn btn-default comment-btn',style: "margin: 1% 0;", data: {status: 'discard'} %>
    <% elsif @submission.discarded? %>
      <%= link_to 'Submit to HM', change_status_job_submission_path(@job, @submission, status: 'process'), class: 'btn btn-default', style: "margin: 1% 0;" %>
      <%#= link_to 'Park', '#', class: 'btn btn-default comment-btn',style: "margin: 1% 0;", data: {status: 'park'} %>
<% end %>
  <% end %>
</div>

<div class="row">
  <div class="comment-section">
    <%= form_tag save_comment_job_submission_path(@job, @submission), class: 'form-horizontal comment_form' do %>
      <%= hidden_field_tag :status, '', class: 'submission_comment_status' %>
      <div class="form-group">
        <div class="col-sm-10">
          <%= text_area_tag :comment, '', class: 'form-control', rows: 4, placeholder: 'Leave your comment here...' %>
        </div>
      </div>
      <div class="col-sm-6 col-sm-offset-3">
        <%= submit_tag :Submit, class: 'btn btn-default btn-block' %>
      </div>
    <% end %>
  </div>
</div>
<style>
  .comment-section{
    margin-top: 10px;
  }

</style>

<script type="text/javascript">
  $('.comment-section').hide();
  $('.comment-btn').on('click', function (e) {
    e.preventDefault();
    $('.comment-section').show(500);
    $('.submission_comment_status').val($(this).data('status'));
  });
</script>

app/views/resumes/_decisions_radio.html.erb
<div class="form-group">
  <div class="btn-group" data-toggle="buttons">
    <% if current_user.hm? %>
      <label class="btn btn-default">
        <input type="radio" name="next_action" value="hire" id="option1" autocomplete="off" required> Hire
      </label>
      <label class="btn btn-default">
        <input type="radio" name="next_action" value="interview" id="option2" autocomplete="off" required> Interview
      </label>
    <% elsif current_user.consultant? %>
      <label class="btn btn-default">
        <input type="radio" name="next_action" value="process" id="option1" autocomplete="off" required> Submit to HM
      </label>
    <% end %>
    <!-- <label class="btn btn-default">
      <input type="radio" name="next_action" value="park" id="option3" autocomplete="off"> Park
    </label>   <br> -->
    <label class="btn btn-default">
      <input type="radio" name="next_action" value="undecided" id="option5" autocomplete="off" required> Undecided
    </label>
    <label class="btn btn-default">
      <input type="radio" name="next_action" value="reject" id="option4" autocomplete="off" required> Reject
    </label>
  </div>
</div>

<div class="form-group comment-block">
  <%= text_area_tag :comment, '', class: 'form-control', placeholder: "Leave your comment here", rows: 4 %>
</div>

<script>
  $("input[name='next_action']").on('change', function() {

    $("input[name='next_action']").each(function(){
      $(this).closest('label').removeClass('btn-success').addClass('btn-default');
    });
    $(this).closest('label').removeClass('btn-default').addClass('btn-success');
  });
</script>

app/views/resumes/show.html.erb
<div class="row">
  <div class="panel panel-default">
    <div class="panel-heading"><%= @submission.user.to_s %></div>
    <div class="panel-body">
      <div class="row">
        <% @resume_sections.each_with_index do |resume_section,i| %>
          <button class="btn section <%= i > 0 ? 'btn-default' : 'btn-success' %>" data-id="<%= resume_section.id %>" type="button">
            <%= resume_section.section %>
          </button>
        <% end %>
      </div>

      <% attachments = @submission.attachments %>
      <% if attachments.any? %>
        <br>
        <div class="row">
          <span><strong>Attachments:</strong></span>
          <% attachments.each do |attachment| %>
                <span>
                  <%= link_to attachment.name, attachment.file.url, target: '_blank' %>
                  <% unless attachment == attachments.last %>,<% end %>
                </span>
          <% end %>
        </div>
        <br>
      <% end %>
      <br>
      <div class="row">
        <div class="col-md-7">
          <% @resume_sections.each_with_index do |resume_section, i| %>
            <div class="video_section sections <%= "hide" if i > 0 %> section_<%= resume_section.id %>">
                <%= video_tag resume_section.video, preload: 'metadata', :size => "500x240", :controls => true, class: 'section_player section_video' %>
            </div>
          <% end %>
        </div>
        <div class="col-md-5">
          <% @resume = @submission.resume %>
          <% if @job.consultant == current_user && @resume_sections.collect(&:consultant_rating).include?(nil) %>
            <div class="row">
              <%= form_for([@job, @submission, @resume], html:{id: 'consultant_rating_form'}) do |f| %>
                <%= f.fields_for :resume_sections do |ff| %>
                  <div class="form-group" style="margin-bottom: 0">
                    <%= ff.label :consultant_rating, ff.object.section %>
                    <%#= ff.collection_radio_buttons :consultant_rating,  (1..5).map { |n| [n, n] }, :first, :last,{}, {class: 'radio-inline form-control', style: 'margin: 10px 5px 10px 10px'} %>
                    <%= ff.hidden_field :consultant_rating, class: 'form-control' %>
                    <p class="star_rating"></p>
                    <span class="help-block rating_hint hide" style="color: #a94442">Rating Required</span>
                  </div>
                <% end %>
                <%= render partial: 'resumes/decisions_radio' %>
                <div class="form-group">
                  <%= f.submit "Submit Rating", class: 'btn btn-small btn-block btn-primary' %>
                </div>
              <% end %>
            </div>
          <% elsif @job.hm == current_user &&  @resume_sections.collect(&:hiring_manager_rating).include?(nil) %>
            <div class="row">
              <%= form_for([@job, @submission, @resume], html:{id: 'hm_rating_form'}) do |f| %>
                <%= f.fields_for :resume_sections do |ff| %>
                  <div class="form-group" style="margin-bottom: 0">
                    <%= ff.label :hiring_manager_rating, ff.object.section %>
                    <%#= ff.collection_radio_buttons :hiring_manager_rating,  (1..5).map { |n| [n, n] }, :first, :last,{}, {class: 'radio-inline form-control', style: 'margin: 10px 5px 10px 10px'} %>
                    <%= ff.hidden_field :hiring_manager_rating, class: 'form-control' %>
                    <p class="star_rating"></p>
                    <span class="help-block rating_hint hide" style="color: #a94442">Rating Required</span>
                  </div>
                <% end %>
                <%= render partial: 'resumes/decisions_radio' %>
                <div class="form-group">
                  <%= f.submit "Submit Rating", class: 'btn btn-small btn-block btn-primary' %>
                </div>
              <% end %>
            </div>
          <% end %>
          <br>
          <div class="row">
            <% @resume_sections.each_with_index do |resume_section, i=0| %>
              <div class="sections <%= "hide" if i > 0 %> section_<%= resume_section.id %>">
                <%= render partial: 'resume_sections/ratings', locals: {resume_section: resume_section} %>
              </div>
            <% end %>
          </div>
          <% if @comments.any? %>
            <div class="row">
              <p><strong>Comments:</strong></p>
              <ul class="well">
                <% @comments.each do |comment| %>
                  <b><%= comment.user.role.label %>:</b>
                  <%= comment.description %>
                <% end %>
              </ul>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  $('.section_video').click(function () {
    this.paused ? this.play() : this.pause();
  });
  $(".section").on('click', function () {
    var id = $(this).data('id');
    var section_id = ".section_" + id;
    $('.sections').addClass('hide');
    $('.section_player').each(function () {
      $(this).get(0).pause(); // pause all videos
    });
    $(section_id).removeClass('hide');
    $('button.section').removeClass('btn-success').addClass('btn-default');
    $(this).removeClass('btn-default').addClass('btn-success')
  });
  $('.star_rating').raty({
    path: '/assets/',
    size: 24,
    starOff: 'star-off-big.png',
    starOn: 'star-on-big.png',
    noRatedMsg  : 'Not rated yet!',
    click: function (score, evt) {
      $(this).prev('input').val(score);
      $(this).next('.rating_hint').remove();
    }
  });

  $('form#consultant_rating_form, form#hm_rating_form').on('submit', function(){
    var scores = $('.star_rating').raty('score');
    var valid = true;
    var decisions = $("input[name='next_action']:checked").length;
    $.each(scores,function(index,value){
      if(value == undefined){
        valid = false;
      }
    });

    if (decisions === 0) {valid = false}

    if(valid){
      return true
    }else{
      $('.rating_hint').removeClass('hide');
      return false
    }

  });

  $('.comment-block').hide();
  $("input[name=next_action]").on('change',function(){
    var val = $(this).val();
    if(val == "park" || val == 'reject'){
      $('.comment-block').show(500);
    }else{
      $('.comment-block').hide(500);
    }
  });
</script>